[window]
opacity = 1
padding.x = 10
padding.y = 10
decorations = "Full"
decorations_theme_variant = "Dark"


[font]
normal.family = "Hack Nerd Font"
bold.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"

